/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AthleteRegistrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedOperators"
      | "categoryMinAges"
      | "checkAgeRequirement"
      | "finalizeDecryption"
      | "finalizeResults"
      | "getAllEncryptedAthleteInfo"
      | "getAthleteAtIndex"
      | "getDecryptedAthleteInfo"
      | "getEncryptedAge"
      | "getEncryptedContact"
      | "getEncryptedData"
      | "getEncryptedName"
      | "getRegistrationTimestamp"
      | "getSportCategory"
      | "getTotalAthletes"
      | "isAthleteRegistered"
      | "protocolId"
      | "registerAthlete"
      | "registerAthleteSimple"
      | "totalAthletes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AthleteInfoUpdated"
      | "AthleteRegistered"
      | "DecryptionResultsAvailable"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "categoryMinAges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAgeRequirement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDecryption",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeResults",
    values: [AddressLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEncryptedAthleteInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAthleteAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedAthleteInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedContact",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSportCategory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAthletes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAthleteRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAthlete",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAthleteSimple",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAthletes",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryMinAges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAgeRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEncryptedAthleteInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAthleteAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedAthleteInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedContact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSportCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAthletes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAthleteRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAthlete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAthleteSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAthletes",
    data: BytesLike
  ): Result;
}

export namespace AthleteInfoUpdatedEvent {
  export type InputTuple = [athlete: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [athlete: string, timestamp: bigint];
  export interface OutputObject {
    athlete: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AthleteRegisteredEvent {
  export type InputTuple = [
    athlete: AddressLike,
    category: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    athlete: string,
    category: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    athlete: string;
    category: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionResultsAvailableEvent {
  export type InputTuple = [
    athlete: AddressLike,
    name: string,
    age: BigNumberish,
    contact: BigNumberish,
    ageRequirementMet: boolean
  ];
  export type OutputTuple = [
    athlete: string,
    name: string,
    age: bigint,
    contact: bigint,
    ageRequirementMet: boolean
  ];
  export interface OutputObject {
    athlete: string;
    name: string;
    age: bigint;
    contact: bigint;
    ageRequirementMet: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AthleteRegistration extends BaseContract {
  connect(runner?: ContractRunner | null): AthleteRegistration;
  waitForDeployment(): Promise<this>;

  interface: AthleteRegistrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  categoryMinAges: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  checkAgeRequirement: TypedContractMethod<[], [string], "nonpayable">;

  finalizeDecryption: TypedContractMethod<
    [
      decryptedName: string,
      decryptedAge: BigNumberish,
      decryptedContact: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  finalizeResults: TypedContractMethod<
    [
      athlete: AddressLike,
      decryptedName: string,
      decryptedAge: BigNumberish,
      decryptedContact: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAllEncryptedAthleteInfo: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        encryptedName: string;
        encryptedAge: string;
        encryptedContact: string;
        sportCategory: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAthleteAtIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getDecryptedAthleteInfo: TypedContractMethod<
    [athlete: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        decryptedName: string;
        decryptedAge: bigint;
        decryptedContact: bigint;
        sportCategory: bigint;
        ageRequirementMet: boolean;
      }
    ],
    "view"
  >;

  getEncryptedAge: TypedContractMethod<[], [string], "view">;

  getEncryptedContact: TypedContractMethod<[], [string], "view">;

  getEncryptedData: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  getEncryptedName: TypedContractMethod<[], [string], "view">;

  getRegistrationTimestamp: TypedContractMethod<[], [bigint], "view">;

  getSportCategory: TypedContractMethod<[], [bigint], "view">;

  getTotalAthletes: TypedContractMethod<[], [bigint], "view">;

  isAthleteRegistered: TypedContractMethod<[], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerAthlete: TypedContractMethod<
    [
      nameHandle: BigNumberish,
      nameInputProof: BytesLike,
      ageHandle: BigNumberish,
      ageInputProof: BytesLike,
      contactHandle: BigNumberish,
      contactInputProof: BytesLike,
      _sportCategory: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerAthleteSimple: TypedContractMethod<
    [
      encryptedName: BytesLike,
      encryptedAge: BytesLike,
      encryptedContact: BytesLike,
      _sportCategory: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalAthletes: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "categoryMinAges"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkAgeRequirement"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeDecryption"
  ): TypedContractMethod<
    [
      decryptedName: string,
      decryptedAge: BigNumberish,
      decryptedContact: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeResults"
  ): TypedContractMethod<
    [
      athlete: AddressLike,
      decryptedName: string,
      decryptedAge: BigNumberish,
      decryptedContact: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllEncryptedAthleteInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        encryptedName: string;
        encryptedAge: string;
        encryptedContact: string;
        sportCategory: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAthleteAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDecryptedAthleteInfo"
  ): TypedContractMethod<
    [athlete: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        decryptedName: string;
        decryptedAge: bigint;
        decryptedContact: bigint;
        sportCategory: bigint;
        ageRequirementMet: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedAge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedContact"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedData"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getEncryptedName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRegistrationTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSportCategory"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalAthletes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAthleteRegistered"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAthlete"
  ): TypedContractMethod<
    [
      nameHandle: BigNumberish,
      nameInputProof: BytesLike,
      ageHandle: BigNumberish,
      ageInputProof: BytesLike,
      contactHandle: BigNumberish,
      contactInputProof: BytesLike,
      _sportCategory: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAthleteSimple"
  ): TypedContractMethod<
    [
      encryptedName: BytesLike,
      encryptedAge: BytesLike,
      encryptedContact: BytesLike,
      _sportCategory: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAthletes"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AthleteInfoUpdated"
  ): TypedContractEvent<
    AthleteInfoUpdatedEvent.InputTuple,
    AthleteInfoUpdatedEvent.OutputTuple,
    AthleteInfoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AthleteRegistered"
  ): TypedContractEvent<
    AthleteRegisteredEvent.InputTuple,
    AthleteRegisteredEvent.OutputTuple,
    AthleteRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionResultsAvailable"
  ): TypedContractEvent<
    DecryptionResultsAvailableEvent.InputTuple,
    DecryptionResultsAvailableEvent.OutputTuple,
    DecryptionResultsAvailableEvent.OutputObject
  >;

  filters: {
    "AthleteInfoUpdated(address,uint256)": TypedContractEvent<
      AthleteInfoUpdatedEvent.InputTuple,
      AthleteInfoUpdatedEvent.OutputTuple,
      AthleteInfoUpdatedEvent.OutputObject
    >;
    AthleteInfoUpdated: TypedContractEvent<
      AthleteInfoUpdatedEvent.InputTuple,
      AthleteInfoUpdatedEvent.OutputTuple,
      AthleteInfoUpdatedEvent.OutputObject
    >;

    "AthleteRegistered(address,uint8,uint256)": TypedContractEvent<
      AthleteRegisteredEvent.InputTuple,
      AthleteRegisteredEvent.OutputTuple,
      AthleteRegisteredEvent.OutputObject
    >;
    AthleteRegistered: TypedContractEvent<
      AthleteRegisteredEvent.InputTuple,
      AthleteRegisteredEvent.OutputTuple,
      AthleteRegisteredEvent.OutputObject
    >;

    "DecryptionResultsAvailable(address,string,uint32,uint32,bool)": TypedContractEvent<
      DecryptionResultsAvailableEvent.InputTuple,
      DecryptionResultsAvailableEvent.OutputTuple,
      DecryptionResultsAvailableEvent.OutputObject
    >;
    DecryptionResultsAvailable: TypedContractEvent<
      DecryptionResultsAvailableEvent.InputTuple,
      DecryptionResultsAvailableEvent.OutputTuple,
      DecryptionResultsAvailableEvent.OutputObject
    >;
  };
}
